# Generated by Django 5.2.4 on 2025-07-10 14:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammaFidelity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_abbonamento', models.CharField(max_length=100)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('sconto_noleggio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Programma Fidelity',
                'verbose_name_plural': 'Programmi Fidelity',
            },
        ),
        migrations.CreateModel(
            name='Videogioco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('genere', models.CharField(max_length=100)),
                ('prezzo_vendita', models.DecimalField(decimal_places=2, max_digits=6)),
                ('prezzo_noleggio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disponibilita', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Videogioco',
                'verbose_name_plural': 'Videogiochi',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('utente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tipo_cliente', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], default='standard', max_length=20)),
                ('id_fidelity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clienti', to='gianluca_app.programmafidelity')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clienti',
            },
            bases=('gianluca_app.utente',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Dipendente',
            fields=[
                ('utente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ruolo', models.CharField(max_length=100)),
                ('codice_staff', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Dipendente',
                'verbose_name_plural': 'Dipendenti',
            },
            bases=('gianluca_app.utente',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Vendita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totale', models.DecimalField(decimal_places=2, max_digits=7)),
                ('data_acquisto', models.DateField(auto_now_add=True)),
                ('tipo_pagamento', models.CharField(max_length=100)),
                ('quantita', models.PositiveIntegerField()),
                ('id_gioco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gianluca_app.videogioco')),
                ('cliente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendite', to='gianluca_app.cliente')),
            ],
            options={
                'verbose_name': 'Vendita',
                'verbose_name_plural': 'Vendite',
            },
        ),
        migrations.CreateModel(
            name='DettaglioVendita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField()),
                ('prezzo_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('id_vendita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettagli', to='gianluca_app.vendita')),
                ('id_gioco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gianluca_app.videogioco')),
            ],
            options={
                'verbose_name': 'Dettaglio Vendita',
                'verbose_name_plural': 'Dettagli Vendita',
            },
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('valutazione', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('data', models.DateField(auto_now_add=True)),
                ('id_gioco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni', to='gianluca_app.videogioco')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni', to='gianluca_app.cliente')),
            ],
            options={
                'verbose_name': 'Recensione',
                'verbose_name_plural': 'Recensioni',
            },
        ),
        migrations.CreateModel(
            name='Noleggio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totale_noleggio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('inizio_noleggio', models.DateField()),
                ('fine_noleggio', models.DateField()),
                ('id_gioco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gianluca_app.videogioco')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noleggi', to='gianluca_app.cliente')),
                ('id_dipendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noleggi', to='gianluca_app.dipendente')),
            ],
            options={
                'verbose_name': 'Noleggio',
                'verbose_name_plural': 'Noleggi',
            },
        ),
    ]
